### ISSUE TITLE
文档和readme能改下吗？

### ISSUE THREAD

**Issue by mjiong** [erbing/vuecn#8]
虽然我是个菜鸟，但是我却发现了，麻烦你改下吧。。

form => from 

`import RunVue form 'runvue'`

**Comment by erbing** [comment]
@mjiong  好的。 3Q

**Comment by erbing** [comment]
@mjiong  欢迎 star  : )

**Comment by mjiong** [comment]
速度真快。。哈哈
不过还有文档那的没改好呢
已star了。希望做的越来越好。
